"""Update schema

Revision ID: 0f4fbf8c80ae
Revises: 381e6bf8e59b
Create Date: 2026-05-24 00:55:35.537637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4fbf8c80ae'
down_revision: Union[str, Sequence[str], None] = '381e6bf8e59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disruption_events', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('disruption_events', sa.Column('recommended_medicines', sa.Text(), nullable=True))
    op.add_column('disruption_events', sa.Column('resolved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disruption_events', 'resolved')
    op.drop_column('disruption_events', 'recommended_medicines')
    op.drop_column('disruption_events', 'description')
    # ### end Alembic commands ###
