"""add_shipment_blockchain_hash_and_fix_notification_read

Revision ID: 381e6bf8e59b
Revises: a1b2c3d4e5f6
Create Date: 2026-05-19 23:37:56.922607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381e6bf8e59b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Shipments: add blockchain_hash column
    op.add_column('shipments', sa.Column('blockchain_hash', sa.String(), nullable=True))

    # Notifications: fix read column from INTEGER to BOOLEAN
    # PostgreSQL requires USING clause for this cast
    op.execute("ALTER TABLE notifications ALTER COLUMN read TYPE BOOLEAN USING read::boolean")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'blockchain_hash')
    op.alter_column('notifications', 'read',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
